### ISSUE TITLE
1080p and 60fps has no sound?

### ISSUE THREAD

**Issue by RavenousMonkeey** [cloudrac3r/cadencegq#2] opened 2018-07-24 22:13 UTC
Is this intended or?

**Comment by cloudrac3r** [comment] 2018-07-24 23:09
YouTube packages high-quality formats (i.e. 1080p and 60fps) differently. (These formats are marked with an exclamation mark `!` in the format list. The audio is in a seperate file from the video and the video is silent. I attempt to work around this by creating an invisible audio player and do my best to keep it in sync with the video player. This works *most of the time.*

If your connection is slow and you can't load the video faster than it plays, you are *not* going to have a good time trying to play that format.

If you switch to a `!` format and you don't hear any sound when playing the video, the audio may not have loaded yet. Pause the video, wait several seconds, and play it again. This works almost every time.

If you still can't hear any audio, open up the web inspector console, type `q("audio")`, then take a screenshot of the last few rows of the console including the command you just typed. After sending me this screenshot along with your operating system, browser, and browser version, stick to formats without a `!` and they should play properly, though unfortunately not in HD.

**Comment by RavenousMonkeey** [comment] 2018-07-25 20:02
I tried again. This time upon opening a video, switch to 1080p first, then hit play. Now the audio plays properly. But if I pause it then unpause, audio disappears. If I seek to another timestamp audio also disappears. 
BTW, if you play it in the default 720p first, then switch to 1080p, the audio won't play.

**Comment by cloudrac3r** [comment] 2018-07-25 22:56
Cannot reproduce. Here's a screen capture of what I see (and what is supposed to happen) from OBS. https://cadence.gq/friends/1080p_demo.mp4 You'll notice that I'm connected to localhost:8080, this is just a local mirror of the website and shouldn't affect anything.

Mind sharing your operating system and browser so I can boot up a virtual machine and try it out in that?

**Comment by RavenousMonkeey** [comment] 2018-07-27 08:56
Vivaldi 1.15.1147.55 64bit
Win10 Pro Version 1709 Build 16299.547

I checked again still same issue.

**Comment by cloudrac3r** [comment] 2018-07-27 09:38
Latest Vivaldi on Windows 8, seems to work fine. I unfortunately do not have a Win 10 VM.

**Comment by cloudrac3r** [comment] 2018-08-01 10:28
If you could get me a screen recording (or screenshots, I guess) with the devtools console open that would be neat.

**Comment by cloudrac3r** [comment] 2018-08-31 10:22
Closing this because I cannot reproduce the issue and you haven't replied in one month. If you'd like to give me more information I'm happy to investigate further.

**Closed as completed by cloudrac3r** 2018-08-31 10:22 UTC
